# Server port
port: 8317
remote-management:
  allow-remote: true
  secret-key: "xxx"
  disable-control-panel: false
  panel-github-repository: https://github.com/router-for-me/Cli-Proxy-API-Management-Center
auth-dir: "/root/.cli-proxy-api"
request-retry: 3
max-retry-interval: 30
api-keys:
  - "xxx"
request-log: false
logging-to-file: false
usage-statistics-enabled: true
quota-exceeded:
  switch-project: true
  switch-preview-model: false
oauth-model-alias:
  antigravity:
    - name: rev19-uic3-1p
      alias: gemini-2.5-computer-use-preview-10-2025
    - name: gemini-3-pro-image
      alias: gemini-3-pro-image-preview
    - name: gemini-3-pro-high
      alias: gemini-3-pro-preview
    - name: gemini-3-flash
      alias: gemini-3-flash-preview
    - name: claude-sonnet-4-5
      alias: gemini-claude-sonnet-4-5
    - name: claude-sonnet-4-5-thinking
      alias: gemini-claude-sonnet-4-5-thinking
    - name: claude-opus-4-5-thinking
      alias: gemini-claude-opus-4-5-thinking
routing:
  strategy: fill-first
